// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkazi-YTcM_pyHgkaBgKgg5AedPjM8sKM',
    appId: '1:940248395110:web:f491737347fc2069caeca7',
    messagingSenderId: '940248395110',
    projectId: 'family-locator-4f676',
    authDomain: 'family-locator-4f676.firebaseapp.com',
    storageBucket: 'family-locator-4f676.appspot.com',
    measurementId: 'G-DLC2MXW14H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMr3agb7C8_98VSo4OtPnaojTcQa0J_ks',
    appId: '1:940248395110:android:ca3c10859a0f0aaacaeca7',
    messagingSenderId: '940248395110',
    projectId: 'family-locator-4f676',
    storageBucket: 'family-locator-4f676.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVji0-qTVknQGNSTicPJ6Wa_YuetFWzz0',
    appId: '1:940248395110:ios:694d1211ad6e2ddfcaeca7',
    messagingSenderId: '940248395110',
    projectId: 'family-locator-4f676',
    storageBucket: 'family-locator-4f676.appspot.com',
    iosBundleId: 'com.kashif.family_room',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVji0-qTVknQGNSTicPJ6Wa_YuetFWzz0',
    appId: '1:940248395110:ios:694d1211ad6e2ddfcaeca7',
    messagingSenderId: '940248395110',
    projectId: 'family-locator-4f676',
    storageBucket: 'family-locator-4f676.appspot.com',
    iosBundleId: 'com.kashif.family_room',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkazi-YTcM_pyHgkaBgKgg5AedPjM8sKM',
    appId: '1:940248395110:web:8f1520fbd9ddd856caeca7',
    messagingSenderId: '940248395110',
    projectId: 'family-locator-4f676',
    authDomain: 'family-locator-4f676.firebaseapp.com',
    storageBucket: 'family-locator-4f676.appspot.com',
    measurementId: 'G-HMZR8Q88RG',
  );
}
